theme: jekyll-theme-tactile
title: Cathedral Sanchez's Internet Asylum
description: What's up! It's your boy Sanchez right here. 
plugins:
  - jemoji
url: "https://97007kim.github.io/cathedral.github.io/"
markdown: kramdown
